### ISSUE TITLE
Issues with PRF Model

### ISSUE THREAD

**Issue by liorbu** [vistalab/vistasoft#91] opened 2013-11-15 19:36 UTC
When running Retinotopy analysis, mrVista crashes after the first ffit with the following error (all output included):

Warning: Your current settings will produce an error in a future release. 
> In fmincon at 510
  In rmSearchFit_oneGaussian at 65
  In rmSearchFit at 339
  In rmMain at 139 
Done [16 minutes].
[rmSearchFit_oneGaussian]:Removed negative fits: 0 (0.0%).
[rmSave]:Saved <removed>/retModel-20131107-160752-sFit.mat.
[reserveToolbox]:optimization toolbox reserved.
[rmMakeTrends]: Removing 6 trends from combined data.
[rmSearchFit]:Processing voxels with variance explained >= 0.00

ans =

     1

ans =

     1

[rmSearchFit_oneGaussian]:Estimated processing time: 185851 voxels: 3 minutes.
[rmSearchFit_oneGaussian]:Nonlinear optimization (x,y,sigma):..........Done [3 minutes].
[rmSearchFit_oneGaussian]:Removed negative fits: 11486 (6.2%).
[rmSave]:Saved <removed>/Gray/Averages/retModel-20131107-160752-fFit.mat.
[reserveToolbox]:optimization toolbox reserved.
[rmMakeTrends]: Removing 6 trends from combined data.

ans =

     1

ans =

     1

[rmHrfSearchFit_oneGaussian]:Making predictions without HRF for each voxel (29762):................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Done[0 min].	(07-Nov-2013 17:14:31)
[hrfModelSearchFit]:Estimating HRF
	Two gamma function:	[peak1 width1 peak2 width2 -weight2]
	Input (Default):	[5.4000 5.2000 10.8000 7.3500 0.3500]
	Search range (min):	[2.7000 2.6000 5.4000 3.6750 0.0000]
	Search range (max):	[10.8000 10.4000 21.6000 14.7000 0.7000]
	Grid stage output:	[5.1300 7.2800 11.8800 8.0850 0.4200] (31 min)
Warning: To use the default trust-region-reflective algorithm you must supply the gradient in the
objective function and set the GradObj option to 'on'. FMINCON will use the active-set algorithm instead.
For information on applicable algorithms, see Choosing the Algorithm in the documentation. 
> In fmincon at 516
  In hrfModelSearchFit at 97
  In rmHrfSearchFit at 247
  In rmMain at 141 
Warning: Your current settings will produce an error in a future release. 
> In fmincon at 526
  In hrfModelSearchFit at 97
  In rmHrfSearchFit at 247
  In rmMain at 141 
Error using fmincon (line 779)
FMINCON requires all values returned by user functions to be of data type double.

Error in hrfModelSearchFit (line 97)
hrfParams = ...

Error in rmHrfSearchFit (line 247)
outParams = hrfModelSearchFit(data,prediction,hrfParams,params);

Error in rmMain (line 141)
        [view,params] = rmHrfSearchFit(view,params);
 
Error while evaluating uimenu Callback

**Comment by JWinawer** [comment] 2015-01-11 18:29
This looks like it might have been an error to do with MATLAB version. In any case, the issue is over a year old and I am closing it. Please re-open if the issue remains un-resolved.

**Closed by JWinawer** 2015-01-11 18:29 UTC

**Comment by allanhummer** [comment] 2015-03-05 16:20
I'm experiencing the same problem using Matlab 8.1 and the current github vistasoft version.

Allan
